export const productList = [
  { name: "Bluetooth Headphones", price: 49.99, category: "Electronics" },
  { name: "Smartphone Charger", price: 12.99, category: "Electronics" },
  { name: "Wireless Mouse", price: 25.5, category: "Electronics" },
  { name: "Gaming Keyboard", price: 79.99, category: "Electronics" },
  { name: "Portable Hard Drive", price: 99.95, category: "Electronics" },
  { name: "Smartwatch", price: 199.0, category: "Electronics" },
  { name: "Laptop Stand", price: 34.99, category: "Electronics" },
  { name: "Noise-Canceling Earbuds", price: 59.99, category: "Electronics" },
  { name: "4K Monitor", price: 299.0, category: "Electronics" },
  { name: "External SSD", price: 129.0, category: "Electronics" },
  { name: "USB Hub", price: 19.99, category: "Electronics" },
  { name: "Desk Lamp", price: 22.5, category: "Furniture" },
  { name: "Ergonomic Chair", price: 149.99, category: "Furniture" },
  { name: "Action Camera", price: 249.0, category: "Electronics" },
  { name: "Tablet Cover", price: 14.99, category: "Electronics" },
  { name: "Wireless Printer", price: 129.99, category: "Electronics" },
  { name: "Smart Thermostat", price: 120.0, category: "Home" },
  { name: "Fitness Tracker", price: 89.99, category: "Electronics" },
  { name: "Portable Speaker", price: 34.95, category: "Electronics" },
  { name: "Laptop Backpack", price: 45.0, category: "Accessories" },
  { name: "Digital Camera", price: 499.0, category: "Electronics" },
  { name: "Home Security Camera", price: 89.99, category: "Home" },
  { name: "Electric Kettle", price: 29.99, category: "Kitchen" },
  { name: "Coffee Maker", price: 69.95, category: "Kitchen" },
  { name: "Air Fryer", price: 89.0, category: "Kitchen" },
  { name: "Blender", price: 49.99, category: "Kitchen" },
  { name: "Slow Cooker", price: 34.0, category: "Kitchen" },
  { name: "Toaster Oven", price: 75.0, category: "Kitchen" },
  { name: "Cordless Vacuum", price: 159.99, category: "Home" },
  { name: "Smart Light Bulbs", price: 24.99, category: "Home" },
  { name: "Robot Vacuum", price: 249.99, category: "Home" },
  { name: "Electric Toothbrush", price: 89.95, category: "Health" },
  { name: "Hair Dryer", price: 45.0, category: "Health" },
  { name: "Curling Iron", price: 29.99, category: "Health" },
  { name: "Digital Alarm Clock", price: 18.5, category: "Home" },
  { name: "Portable Power Bank", price: 22.0, category: "Electronics" },
  { name: "Wireless Earbuds", price: 65.0, category: "Electronics" },
  { name: "Home Humidifier", price: 55.0, category: "Home" },
  { name: "Dehumidifier", price: 129.0, category: "Home" },
  { name: "Electric Blanket", price: 79.99, category: "Home" },
  { name: "Weighted Blanket", price: 99.0, category: "Home" },
  { name: "Fitness Bike", price: 299.0, category: "Fitness" },
  { name: "Treadmill", price: 699.0, category: "Fitness" },
  { name: "Massage Chair", price: 1299.0, category: "Furniture" },
  { name: "Camping Tent", price: 149.95, category: "Outdoor" },
  { name: "Sleeping Bag", price: 45.0, category: "Outdoor" },
  { name: "Hiking Boots", price: 99.95, category: "Outdoor" },
  { name: "Portable Grill", price: 69.99, category: "Outdoor" },
  { name: "Camping Lantern", price: 24.99, category: "Outdoor" },
  { name: "Cooler Box", price: 59.95, category: "Outdoor" },
];
